"""Self-contained HTML report template for ``replayt report`` (no external CDN)."""

from __future__ import annotations

import html
import json
from typing import Any

REPORT_CSS = """
:root {{
  --slate-50: #f8fafc; --slate-100: #f1f5f9; --slate-200: #e2e8f0; --slate-300: #cbd5e1;
  --slate-400: #94a3b8; --slate-500: #64748b; --slate-600: #475569; --slate-700: #334155;
  --slate-800: #1e293b; --slate-900: #0f172a;
  --green-100: #dcfce7; --green-500: #22c55e; --green-800: #166534;
  --red-100: #fee2e2; --red-500: #ef4444; --red-800: #991b1b;
  --yellow-100: #fef9c3; --yellow-800: #854d0e;
}}
body.rp-body {{ margin:0; min-height:100vh; background:var(--slate-50); color:var(--slate-900);
  font-family:ui-sans-serif,system-ui,sans-serif; -webkit-font-smoothing:antialiased; }}
.rp-main {{ max-width:56rem; margin:0 auto; padding:2.5rem 1rem; }}
.rp-section {{ margin-bottom:2rem; }}
.rp-h1 {{ font-size:1.5rem; font-weight:700; letter-spacing:-0.025em; margin:0 0 0.5rem; }}
.rp-h2 {{ font-size:1.125rem; font-weight:600; margin:0 0 0.75rem; }}
.rp-card {{ background:#fff; border:1px solid var(--slate-200); border-radius:0.5rem;
  box-shadow:0 1px 2px rgba(15,23,42,0.06); padding:1.25rem; }}
.rp-card-tight p {{ margin:0.15rem 0; font-size:0.875rem; }}
.rp-label {{ font-weight:500; color:var(--slate-500); }}
.rp-code {{ font-family:ui-monospace,monospace; color:var(--slate-800); font-size:0.9em; }}
.rp-badge {{
  display:inline-block; padding:0.125rem 0.5rem; border-radius:0.25rem; font-size:0.75rem; font-weight:600;
}}
.rp-badge-ok {{ background:var(--green-100); color:var(--green-800); }}
.rp-badge-err {{ background:var(--red-100); color:var(--red-800); }}
.rp-badge-pause {{ background:var(--yellow-100); color:var(--yellow-800); }}
.rp-badge-neutral {{ background:var(--slate-100); color:var(--slate-800); }}
.rp-timeline {{ list-style:none; margin:0; padding:0 0 0 0.75rem; border-left:2px solid var(--slate-300); }}
.rp-tl-item {{ position:relative; margin-bottom:1rem; margin-left:0.5rem; }}
.rp-tl-dot {{ position:absolute; left:-1.15rem; top:0.2rem; width:0.65rem; height:0.65rem;
  border-radius:9999px; border:2px solid #fff; }}
.rp-dot-muted {{ background:var(--slate-400); }}
.rp-dot-ok {{ background:var(--green-500); }}
.rp-dot-err {{ background:var(--red-500); }}
.rp-tl-state {{ font-size:0.875rem; font-weight:500; color:var(--slate-700); margin:0; }}
.rp-tl-ts {{ font-size:0.75rem; color:var(--slate-400); margin:0.15rem 0 0; }}
.rp-muted {{ color:var(--slate-400); font-size:0.875rem; }}
.rp-stack {{ display:flex; flex-direction:column; gap:0.75rem; }}
details.rp-details summary {{
  cursor:pointer; font-size:0.875rem; font-weight:500; color:var(--slate-700); list-style:none;
}}
details.rp-details summary::-webkit-details-marker {{ display:none; }}
details.rp-details summary:hover {{ color:var(--slate-900); }}
.rp-pre {{ margin-top:0.5rem; padding:0.75rem; background:var(--slate-50); border-radius:0.375rem;
  font-size:0.75rem; color:var(--slate-600); border:1px solid var(--slate-100);
  white-space:pre-wrap; word-break:break-all; }}
.rp-divide > * + * {{ border-top:1px solid var(--slate-100); }}
.rp-tc-item {{ padding:1rem; }}
.rp-table {{ width:100%; text-align:left; font-size:0.875rem; border-collapse:collapse; }}
.rp-table th, .rp-table td {{ padding:0.25rem 0; }}
.rp-table th {{ font-weight:500; color:var(--slate-500); }}
.rp-table .rp-num {{ text-align:right; font-family:ui-monospace,monospace; }}
.rp-table thead tr {{ border-bottom:1px solid var(--slate-200); }}
.rp-table tbody tr.rp-total {{ border-top:1px solid var(--slate-200); font-weight:600; }}
.rp-foot {{ font-size:0.75rem; color:var(--slate-400); margin-top:3rem; }}
.rp-seq {{ font-size:0.75rem; color:var(--slate-400); font-weight:400; }}
"""

REPORT_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>replayt report &mdash; {run_id}</title>
  <style>
""" + REPORT_CSS + """
  </style>
</head>
<body class="rp-body">
  <main class="rp-main">

    <section class="rp-section">
      <h1 class="rp-h1">{report_title}</h1>
      <div class="rp-card rp-card-tight">
        <p><span class="rp-label">Run ID:</span> <code class="rp-code">{run_id}</code></p>
        <p><span class="rp-label">Workflow:</span> {workflow_name}@{workflow_version}</p>
        <p><span class="rp-label">Status:</span>
          <span class="rp-badge {status_class}">{status}</span></p>
        <p><span class="rp-label">Duration:</span> {duration}</p>
        {tags_html}
        {meta_html}
      </div>
    </section>

    {approvals_section}

    <section class="rp-section">
      <h2 class="rp-h2">State Timeline</h2>
      <div class="rp-card">
        <ol class="rp-timeline">
          {timeline_html}
        </ol>
      </div>
    </section>

    {outputs_section}

    {tool_calls_section}

    {token_section}

    <footer class="rp-foot">Generated by replayt</footer>
  </main>
</body>
</html>
"""

TIMELINE_ITEM = """\
<li class="rp-tl-item">
  <span class="rp-tl-dot {dot_class}"></span>
  <p class="rp-tl-state">{state}</p>
  <p class="rp-tl-ts">{ts}</p>
</li>"""

OUTPUTS_SECTION = """\
    <section class="rp-section">
      <h2 class="rp-h2">Structured Outputs</h2>
      <div class="rp-card rp-stack">
        {items}
      </div>
    </section>"""

OUTPUT_ITEM = """\
<details class="rp-details group">
  <summary>{schema_name}</summary>
  <pre class="rp-pre">{data_json}</pre>
</details>"""

TOOL_CALLS_SECTION = """\
    <section class="rp-section">
      <h2 class="rp-h2">Tool Calls</h2>
      <div class="rp-card rp-divide">
        {items}
      </div>
    </section>"""

TOOL_CALL_ITEM = """\
<details class="rp-details rp-tc-item">
  <summary>{tool} <span class="rp-seq">(seq {seq})</span></summary>
  <pre class="rp-pre">{detail_json}</pre>
</details>"""

TOKEN_USAGE_SECTION = """\
    <section class="rp-section">
      <h2 class="rp-h2">Token Usage</h2>
      <div class="rp-card rp-card-tight">
        <table class="rp-table">
          <thead><tr>
            <th>Metric</th><th class="rp-num">Value</th>
          </tr></thead>
          <tbody>
            <tr><td>Prompt tokens</td><td class="rp-num">{prompt_tokens}</td></tr>
            <tr><td>Completion tokens</td><td class="rp-num">{completion_tokens}</td></tr>
            <tr class="rp-total"><td>Total tokens</td><td class="rp-num">{total_tokens}</td></tr>
          </tbody>
        </table>
      </div>
    </section>"""

APPROVALS_SECTION = """\
    <section class="rp-section">
      <h2 class="rp-h2">Approvals</h2>
      <div class="rp-card rp-stack">
        {items}
      </div>
    </section>"""

APPROVAL_ITEM = """\
<div class="rp-card rp-card-tight" style="border:1px solid var(--slate-200);">
  <p><span class="rp-label">Approval ID:</span> <code class="rp-code">{approval_id}</code></p>
  <p><span class="rp-label">State:</span> {state}</p>
  <p><span class="rp-label">Summary:</span> {summary}</p>
  <p><span class="rp-label">Outcome:</span> <strong>{outcome}</strong></p>
</div>"""


def collect_report_context(events: list[dict[str, Any]]) -> dict[str, Any]:
    """Parse events into the same shape ``cmd_report`` uses (for single-run and diff reports)."""

    workflow_name = ""
    workflow_version = ""
    status = "unknown"
    tags: dict[str, str] = {}
    run_metadata: dict[str, Any] = {}
    states: list[dict[str, str]] = []
    outputs: list[dict[str, Any]] = []
    tool_calls: list[dict[str, Any]] = []
    prompt_tokens = 0
    completion_tokens = 0
    total_tokens = 0
    first_ts: str | None = None
    last_ts: str | None = None
    approval_requests: dict[str, dict[str, Any]] = {}
    approval_last: dict[str, bool] = {}

    for e in events:
        ts = e.get("ts", "")
        if first_ts is None:
            first_ts = ts
        last_ts = ts
        typ = e.get("type")
        payload = e.get("payload") or {}

        if typ == "run_started":
            workflow_name = str(payload.get("workflow_name", ""))
            workflow_version = str(payload.get("workflow_version", ""))
            tags = payload.get("tags") or {}
            run_metadata = payload.get("run_metadata") or {}
        elif typ == "state_entered":
            states.append({"state": str(payload.get("state", "")), "ts": ts})
        elif typ == "structured_output":
            outputs.append({"schema_name": payload.get("schema_name", ""), "data": payload.get("data")})
        elif typ == "tool_call":
            tool_calls.append({
                "tool": payload.get("name", ""), "seq": e.get("seq", ""), "args": payload.get("arguments"),
            })
        elif typ == "tool_result":
            tool_calls.append({
                "tool": payload.get("name", "result"),
                "seq": e.get("seq", ""),
                "args": payload.get("result"),
            })
        elif typ == "llm_response":
            usage = payload.get("usage") or {}
            pt = usage.get("prompt_tokens")
            ct = usage.get("completion_tokens")
            tt = usage.get("total_tokens")
            if isinstance(pt, int):
                prompt_tokens += pt
            if isinstance(ct, int):
                completion_tokens += ct
            if isinstance(tt, int):
                total_tokens += tt
        elif typ == "run_completed":
            status = str(payload.get("status", status))
        elif typ == "run_paused":
            status = "paused"
        elif typ == "run_failed":
            status = "failed"
        elif typ == "approval_requested":
            aid = payload.get("approval_id")
            if aid is not None:
                approval_requests[str(aid)] = {
                    "summary": payload.get("summary", ""),
                    "state": payload.get("state", ""),
                }
        elif typ == "approval_resolved":
            aid = payload.get("approval_id")
            if aid is not None:
                approval_last[str(aid)] = bool(payload.get("approved"))

    return {
        "workflow_name": workflow_name,
        "workflow_version": workflow_version,
        "status": status,
        "tags": tags,
        "run_metadata": run_metadata,
        "states": states,
        "outputs": outputs,
        "tool_calls": tool_calls,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
        "first_ts": first_ts,
        "last_ts": last_ts,
        "approval_requests": approval_requests,
        "approval_last": approval_last,
    }


def _outputs_signature(outputs: list[dict[str, Any]]) -> dict[str, Any]:
    return {str(o.get("schema_name", "")): o.get("data") for o in outputs}


REPORT_DIFF_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>replayt report diff</title>
  <style>
""" + REPORT_CSS + """
.rp-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:1rem; }}
@media (max-width:48rem) {{ .rp-grid {{ grid-template-columns:1fr; }} }}
.rp-diff-row {{ font-size:0.875rem; margin:0.25rem 0; }}
.rp-changed {{ color:var(--red-800); font-weight:600; }}
  </style>
</head>
<body class="rp-body">
  <main class="rp-main">
    <section class="rp-section">
      <h1 class="rp-h1">Run comparison</h1>
      <p class="rp-muted">Side-by-side summary from recorded JSONL (no model calls).</p>
    </section>
    <section class="rp-section rp-grid">
      <div class="rp-card rp-card-tight">
        <h2 class="rp-h2">Run A</h2>
        <p><span class="rp-label">ID:</span> <code class="rp-code">{run_a}</code></p>
        <p><span class="rp-label">Workflow:</span> {wa_name}@{wa_ver}</p>
        <p><span class="rp-label">Status:</span> {wa_status}</p>
        <p><span class="rp-label">States:</span> {wa_states}</p>
      </div>
      <div class="rp-card rp-card-tight">
        <h2 class="rp-h2">Run B</h2>
        <p><span class="rp-label">ID:</span> <code class="rp-code">{run_b}</code></p>
        <p><span class="rp-label">Workflow:</span> {wb_name}@{wb_ver}</p>
        <p><span class="rp-label">Status:</span> {wb_status}</p>
        <p><span class="rp-label">States:</span> {wb_states}</p>
      </div>
    </section>
    <section class="rp-section">
      <h2 class="rp-h2">Structured outputs</h2>
      <div class="rp-card">
        {outputs_diff_rows}
      </div>
    </section>
    <section class="rp-section">
      <h2 class="rp-h2">Approvals</h2>
      <div class="rp-card rp-card-tight">
        {approvals_diff}
      </div>
    </section>
    <footer class="rp-foot">Generated by replayt</footer>
  </main>
</body>
</html>"""


def build_report_diff_html(
    run_a: str,
    run_b: str,
    ctx_a: dict[str, Any],
    ctx_b: dict[str, Any],
) -> str:
    def state_chain(states: list[dict[str, str]]) -> str:
        return " → ".join(s["state"] for s in states) if states else "(none)"

    sa = _outputs_signature(ctx_a["outputs"])
    sb = _outputs_signature(ctx_b["outputs"])
    keys = sorted(set(sa) | set(sb))
    rows: list[str] = []
    for k in keys:
        va, vb = sa.get(k), sb.get(k)
        same = va == vb
        cls = "rp-diff-row" if same else "rp-diff-row rp-changed"
        rows.append(
            f'<p class="{cls}"><span class="rp-label">{html.escape(k)}:</span> '
            f"{'match' if same else 'different'}</p>"
            + (
                ""
                if same
                else f'<pre class="rp-pre">A: {html.escape(json.dumps(va, indent=2, default=str)[:1200])}\n\n'
                f'B: {html.escape(json.dumps(vb, indent=2, default=str)[:1200])}</pre>'
            )
        )
    if not rows:
        rows.append('<p class="rp-muted">No structured_output events in either run.</p>')

    ar, br = ctx_a["approval_requests"], ctx_b["approval_requests"]
    appr = "A approvals: " + str(len(ar)) + " — B approvals: " + str(len(br))
    if ar != br:
        appr += " (counts or ids differ — open single-run reports for detail)"

    return REPORT_DIFF_HTML.format(
        run_a=html.escape(run_a),
        run_b=html.escape(run_b),
        wa_name=html.escape(str(ctx_a["workflow_name"])),
        wa_ver=html.escape(str(ctx_a["workflow_version"])),
        wa_status=html.escape(str(ctx_a["status"])),
        wa_states=html.escape(state_chain(ctx_a["states"])),
        wb_name=html.escape(str(ctx_b["workflow_name"])),
        wb_ver=html.escape(str(ctx_b["workflow_version"])),
        wb_status=html.escape(str(ctx_b["status"])),
        wb_states=html.escape(state_chain(ctx_b["states"])),
        outputs_diff_rows="\n".join(rows),
        approvals_diff=html.escape(appr),
    )
